# Generated by Django 5.0.3 on 2024-05-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DDeatils",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "d_id",
                    models.CharField(db_column="D_ID", max_length=200, unique=True),
                ),
                ("d_name", models.CharField(db_column="D_Name", max_length=200)),
                ("d_picurl", models.ImageField(upload_to="photos/")),
                (
                    "d_fathername",
                    models.CharField(db_column="D_FatherName", max_length=255),
                ),
                ("d_address", models.TextField(db_column="D_Address")),
                (
                    "d_religion",
                    models.CharField(db_column="D_Religion", max_length=150),
                ),
                (
                    "d_maritalstatus",
                    models.CharField(db_column="D_MaritalStatus", max_length=100),
                ),
                ("d_mobno", models.BigIntegerField(db_column="D_MobNo")),
                (
                    "d_destination",
                    models.CharField(db_column="D_Destination", max_length=150),
                ),
                ("d_duration", models.CharField(db_column="D_Duration", max_length=80)),
                (
                    "d_routeuse",
                    models.CharField(db_column="D_RouteUse", max_length=150),
                ),
                (
                    "d_placevislastyear",
                    models.CharField(db_column="D_PlaceVisLastYear", max_length=50),
                ),
                (
                    "d_familydeatils",
                    models.JSONField(
                        blank=True, db_column="D_FamilyDeatils", null=True
                    ),
                ),
                (
                    "d_deradetails",
                    models.JSONField(blank=True, db_column="D_DeraDetails", null=True),
                ),
            ],
            options={
                "db_table": "d_deatils",
                "managed": False,
            },
        ),
    ]
